replicaCount: 1

image:
  repository: loupeznik/go-postgres-connection-test
  pullPolicy: IfNotPresent
  tag: "1.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80

db:
  connectionString: ""

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: go-db-connection-test.deploy.aks-dz-kube-test-01.dzarsky.eu
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
