apiVersion: v1
kind: Service
metadata:
  name: {{include "go-db-connection-test.fullname" .}}
  labels: {{- include "go-db-connection-test.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "go-db-connection-test.selectorLabels" . | nindent 4}}
